// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfpglvdilzqoapvfmnqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmcGdsdmRpbHpxb2FwdmZtbnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTgzNzUsImV4cCI6MjA1NTczNDM3NX0.pkaj4JsVNv4hsBE7_sYO3z4r2ZR0i8D3WKocvMHNFmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);